name: build
on: [push, pull_request]

jobs:
  format-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.9"

      - name: Setup Python
        run: uv python install 3.12

      - name: Install Dependencies
        run: make install

      - name: Run Tests
        run: make test